import { PropertyItem } from './types';

export const YAMUNA_EXPRESSWAY_LISTINGS: PropertyItem[] = [
  { id: 1, region: 'Yamuna Expressway', sector: 'SEC-18 PKT-1', details: 'Sector 18, Pocket 1, Yamuna Expressway Authority Plots', blocks: 'A, B', size: '300 MTR' },
  { id: 2, region: 'Yamuna Expressway', sector: 'SEC-18 PKT-2', details: 'Sector 18, Pocket 2, Yamuna Expressway Authority Plots', blocks: 'A, B, C', size: '300 MTR' },
  { id: 3, region: 'Yamuna Expressway', sector: 'SEC-18 PKT-3', details: 'Sector 18, Pocket 3, Yamuna Expressway Authority Plots', blocks: 'A, B, C, D', size: '300 MTR' },
  { id: 4, region: 'Yamuna Expressway', sector: 'SEC-18 PKT-4', details: 'Sector 18, Pocket 4, Yamuna Expressway Authority Plots', blocks: 'A', size: '300 MTR' },
  { id: 5, region: 'Yamuna Expressway', sector: 'SEC-18 PKT-5', details: 'Sector 18, Pocket 5, Yamuna Expressway Authority Plots', blocks: 'A, B, C, D', size: '300 MTR' },
  { id: 6, region: 'Yamuna Expressway', sector: 'SEC-18 PKT-6', details: 'Sector 18, Pocket 6, Yamuna Expressway Authority Plots', blocks: 'A, B, C, D', size: '300 MTR' },
  { id: 7, region: 'Yamuna Expressway', sector: 'SEC-18 PKT-7', details: 'Sector 18, Pocket 7, Yamuna Expressway Authority Plots', blocks: 'A, B, C, D, E, F', size: '300 MTR' },
  { id: 8, region: 'Yamuna Expressway', sector: 'SEC-18 BLK-I,J', details: 'Sector 18, Block I & Block J Residential Plots', blocks: 'I, J', size: '300 MTR' },
  { id: 9, region: 'Yamuna Expressway', sector: 'SEC-20 (A, B)', details: 'Sector 20, Pocket A & B Premium Authority Plots', blocks: 'A, B', size: '4000/2000 MTR' },
  { id: 10, region: 'Yamuna Expressway', sector: 'SEC-20 (C,D,E,F,G,H)', details: 'Sector 20, Block C, D, E, F, G, H Premium Authority Plots', blocks: 'C, D, E, F, G, H', size: '300 MTR' },
  { id: 11, region: 'Yamuna Expressway', sector: 'SEC-20 (K,L,M,O,P)', details: 'Sector 20, Block K, L, M, O, P Premium Authority Plots', blocks: 'K, L, M, O, P', size: '300 MTR' },
  { id: 12, region: 'Yamuna Expressway', sector: 'SEC-20 (Q,R,S,T,U)', details: 'Sector 20, Block Q, R, S, T, U Premium Authority Plots', blocks: 'Q, R, S, T, U', size: '500 MTR' }
];

export const GREATER_NOIDA_LISTINGS: PropertyItem[] = [
  {
    id: 101,
    region: 'Greater Noida',
    sector: 'ALPHA-I',
    details: '3 BHK Premium High-Rise Apartment near Active Metro Belt. Semi-furnished with modular kitchen, wardrobes, wood flooring, and double balconies.',
    blocks: 'A, B, C',
    size: '1650 Sq.Ft.',
    price: '₹ 1.95 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '3 BHK Flat',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 102,
    region: 'Greater Noida',
    sector: 'ALPHA-II',
    details: '200 Sq. Mtr. Residential Authority Corner Plot. East facing, 12-meter wide road, near commercial community market.',
    blocks: 'F, G, H',
    size: '200 MTR',
    price: '₹ 2.40 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: 'Plot',
    agentName: 'Anil Kumar'
  },
  {
    id: 103,
    region: 'Greater Noida',
    sector: 'BETA-I',
    details: '4 BHK Independent Duplex Villa with Private Front Lawn. Built-up premium structure, marble flooring, and double servant quarters.',
    blocks: 'A, B, L',
    size: '300 MTR',
    price: '₹ 3.80 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '4 BHK Villa',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 104,
    region: 'Greater Noida',
    sector: 'BETA-II',
    details: 'Urgent Buy Requirement for 120 Mtr Plot. Clear title preferred, ready for immediate payment, budget up to ₹ 1.50 Cr.',
    blocks: 'F, G, I',
    size: '120 MTR',
    price: '₹ 1.50 Cr Budget',
    photoUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=300&q=80',
    purpose: 'Buy',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: 'Plot Wanted',
    agentName: 'Anil Kumar'
  },
  {
    id: 105,
    region: 'Greater Noida',
    sector: 'GAMMA-I',
    details: '3 BHK Executive Floor on Ground Level. Garden facing block, direct Registry, close to Alpha Commercial Metro.',
    blocks: 'C, D, E',
    size: '1450 Sq.Ft.',
    price: '₹ 1.35 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '3 BHK Flat',
    agentName: 'Ravi Sharma'
  },
  {
    id: 106,
    region: 'Greater Noida',
    sector: 'GAMMA-II',
    details: 'Commercial Office Space / Corporate Showroom on main 24m road. Glass elevation, premium visual positioning, high footfall area.',
    blocks: 'G, H, J',
    size: '850 Sq.Ft.',
    price: '₹ 95 Lakhs',
    photoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: 'Commercial Shop',
    agentName: 'Sanjay Dutt'
  },
  {
    id: 107,
    region: 'Greater Noida',
    sector: 'DELTA-I',
    details: 'Beautiful 2 BHK Semi-Furnished Flat in low-rise authority gated complex. Reserved parking space, 24/7 security guards.',
    blocks: 'A, B, D',
    size: '1050 Sq.Ft.',
    price: '₹ 78 Lakhs',
    photoUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '2 BHK Flat',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 108,
    region: 'Greater Noida',
    sector: 'DELTA-II',
    details: 'Immediate requirement to Buy a 150 Mtr plot. Pocket F or G preferred, park facing with clear registry documents.',
    blocks: 'G, H, I',
    size: '150 MTR',
    price: '₹ 1.85 Cr Budget',
    photoUrl: 'https://images.unsplash.com/photo-1524813686514-a57563d77d61?auto=format&fit=crop&w=300&q=80',
    purpose: 'Buy',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: 'Plot Wanted',
    agentName: 'Anil Kumar'
  },
  {
    id: 109,
    region: 'Greater Noida',
    sector: 'DELTA-III',
    details: '3 BHK Independent Luxury Builder Floor. Top brand fittings, false ceiling with ambient LED strip, stilt car parking block.',
    blocks: 'L, M, P',
    size: '1550 Sq.Ft.',
    price: '₹ 1.25 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '3 BHK Flat',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 110,
    region: 'Greater Noida',
    sector: 'P3',
    details: '2 BHK Independent Ground Floor Unit. Spacious front courtyard, marble flooring, close to Pari Chowk expressway junction.',
    blocks: 'A, B',
    size: '1150 Sq.Ft.',
    price: '₹ 85 Lakhs',
    photoUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: '2 BHK Flat',
    agentName: 'Anil Kumar'
  },
  {
    id: 111,
    region: 'Greater Noida',
    sector: 'SWARN NAGARI',
    details: '500 Mtr Ultra Luxury Elite Mansion. Facing central mega-park, 5 master bedrooms, home theater, private swimming pool, modular bar counter.',
    blocks: 'A, B, C',
    size: '500 MTR',
    price: '₹ 5.95 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '5 BHK Mansion',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 112,
    region: 'Greater Noida',
    sector: 'SIGMA-I',
    details: '3 BHK Luxury High-End Villa. Newly constructed under expert engineering supervision, modular woodwork, and automatic gate installation.',
    blocks: 'A, B',
    size: '200 MTR',
    price: '₹ 2.80 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: '3 BHK Villa',
    agentName: 'Ravi Sharma'
  },
  {
    id: 113,
    region: 'Greater Noida',
    sector: 'SIGMA-II',
    details: '300 Sq. Mtr. Premium Authority Corner Plot. Park facing, adjacent to standard green belt corridor, perfect for elite multi-floor villa.',
    blocks: 'C, D',
    size: '300 MTR',
    price: '₹ 3.45 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: 'Plot',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 114,
    region: 'Greater Noida',
    sector: 'SIGMA-III',
    details: 'Immediate Buy Requirement for 162 Mtr Premium Plot. Block A or B preferred. Budget up to ₹ 1.95 Cr based on depth & location.',
    blocks: 'A, B',
    size: '162 MTR',
    price: '₹ 1.95 Cr Budget',
    photoUrl: 'https://images.unsplash.com/photo-1475855581690-80accde3ae2b?auto=format&fit=crop&w=300&q=80',
    purpose: 'Buy',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: 'Plot Wanted',
    agentName: 'Anil Kumar'
  },
  {
    id: 115,
    region: 'Greater Noida',
    sector: 'SIGMA-IV',
    details: '4 BHK Ultra Luxury Duplex Villa with premium interior styling. Modular Italian kitchen, false ceiling, private elevator, and modular washroom fittings.',
    blocks: 'A, B, C',
    size: '325 MTR',
    price: '₹ 4.10 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '4 BHK Duplex',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 116,
    region: 'Greater Noida',
    sector: 'SECTOR-36',
    details: '3 BHK Spacious High-Rise Apartment. Excellent ventilation, premium wardrobes, double storage boxes, ready for immediate registration.',
    blocks: 'B, C, D',
    size: '1500 Sq.Ft.',
    price: '₹ 1.10 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: '3 BHK Flat',
    agentName: 'Anil Kumar'
  },
  {
    id: 117,
    region: 'Greater Noida',
    sector: 'SECTOR-37',
    details: 'Buyer looking for 120 Mtr Plot. Budget is flexible up to ₹ 1.40 Cr. Immediate registry expected, clear chain deeds wanted.',
    blocks: 'A, B',
    size: '120 MTR',
    price: '₹ 1.40 Cr Budget',
    photoUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=300&q=80',
    purpose: 'Buy',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: 'Plot Wanted',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 118,
    region: 'Greater Noida',
    sector: 'CHI-PHI',
    details: '4 BHK Luxury Golf-Facing Condominium. 100% uninterrupted view of 18-hole golf course, private lobby entrance, Italian marble flooring.',
    blocks: 'A, B',
    size: '2450 Sq.Ft.',
    price: '₹ 3.10 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '4 BHK Flat',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 119,
    region: 'Greater Noida',
    sector: 'ETA-II',
    details: '3 BHK Ready-to-move Flat in highly secure society. Low-maintenance setup with round-the-clock power backup, kids play garden, and gym.',
    blocks: 'A, B',
    size: '1350 Sq.Ft.',
    price: '₹ 89 Lakhs',
    photoUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: '3 BHK Flat',
    agentName: 'Anil Kumar'
  },
  {
    id: 120,
    region: 'Greater Noida',
    sector: 'MU-I',
    details: 'Urgent Resale of 200 Mtr Corner Plot. Clear allotment from Noida Authority, single-owner registry, direct face-to-face table discussion.',
    blocks: 'C, D',
    size: '200 MTR',
    price: '₹ 2.55 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: 'Plot',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 121,
    region: 'Greater Noida',
    sector: 'OMICRON-IA',
    details: '3 BHK Premium Flat in upscale township. High floor with spectacular panoramic views of Noida Expressway corridor, modular wood furnishings.',
    blocks: 'A, B',
    size: '1480 Sq.Ft.',
    price: '₹ 1.15 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: '3 BHK Flat',
    agentName: 'Anil Kumar'
  },
  {
    id: 122,
    region: 'Greater Noida',
    sector: 'OMICRON-II',
    details: '3 BHK Deluxe apartment on intermediate level floor. Dual balconies, modular kitchen, chimney installed, closed covered parking included.',
    blocks: 'C, D',
    size: '1380 Sq.Ft.',
    price: '₹ 98 Lakhs',
    photoUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '3 BHK Flat',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 123,
    region: 'Greater Noida',
    sector: 'OMICRON-III',
    details: '200 Sq. Mtr. Residential plot near main Greater Noida Link Road. Clear ownership title, close to commercial retail shopping complex block.',
    blocks: 'A, B',
    size: '200 MTR',
    price: '₹ 2.20 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: 'Plot',
    agentName: 'Anil Kumar'
  },
  {
    id: 124,
    region: 'Greater Noida',
    sector: 'XU-I',
    details: '3 BHK spacious independent builder floor unit with absolute private terrace rights. Ultra modular fittings and high-end security gate locks.',
    blocks: 'A, B, C',
    size: '1600 Sq.Ft.',
    price: '₹ 1.28 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '3 BHK Flat',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 125,
    region: 'Greater Noida',
    sector: 'XU-II',
    details: 'Buyer looking for compact 120 Mtr Plot. Budget strictly up to ₹ 1.30 Cr. Immediate deal finalization preferred with downpayment terms.',
    blocks: 'A, B',
    size: '120 MTR',
    price: '₹ 1.30 Cr Budget',
    photoUrl: 'https://images.unsplash.com/photo-1524813686514-a57563d77d61?auto=format&fit=crop&w=300&q=80',
    purpose: 'Buy',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: 'Plot Wanted',
    agentName: 'Anil Kumar'
  },
  {
    id: 126,
    region: 'Greater Noida',
    sector: 'XU-III',
    details: '2 BHK affordable low-rise apartment unit. Uninterrupted municipal water supply, close to upcoming public sector utility school hubs.',
    blocks: 'A, B, D',
    size: '950 Sq.Ft.',
    price: '₹ 58 Lakhs',
    photoUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '2 BHK Flat',
    agentName: 'Ravi Sharma'
  },
  {
    id: 127,
    region: 'Greater Noida',
    sector: 'SECTOR-2 (W)',
    details: '200 Sq. Mtr. Premium Sector 2 plot (Greater Noida West / Noida Extension). Highly appreciating corridor, perfect investment profile.',
    blocks: 'A, B, C',
    size: '200 MTR',
    price: '₹ 1.90 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: 'Plot',
    agentName: 'Anil Kumar'
  },
  {
    id: 128,
    region: 'Greater Noida',
    sector: 'SECTOR-3 (W)',
    details: '3 BHK Brand New High-Rise Flat. Gated society, ultra luxurious clubhouse access, semi-furnished with direct power backup and modular wardrobes.',
    blocks: 'G, H',
    size: '1450 Sq.Ft.',
    price: '₹ 1.20 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '3 BHK Flat',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 129,
    region: 'Greater Noida',
    sector: 'EKANKI',
    details: '4 BHK premium modern duplex with private stilt floor parking. False ceiling with remote LEDs, highly secure society layout design.',
    blocks: 'A, B',
    size: '2100 Sq.Ft.',
    price: '₹ 1.98 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: '4 BHK Duplex',
    agentName: 'Ravi Sharma'
  },
  {
    id: 130,
    region: 'Greater Noida',
    sector: 'NRI CITY',
    details: '5 BHK Ultra Luxury Duplex Mansion in the highly premium NRI City gated enclave. Gated golf views, private garden, top tier luxury parameters.',
    blocks: 'A, B',
    size: '450 MTR',
    price: '₹ 5.50 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '5 BHK Mansion',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 131,
    region: 'Greater Noida',
    sector: 'PARI CHOWK ENCLAVE',
    details: 'Commercial Office Space & Premium Retail Shop block at iconic Pari Chowk. Ground floor, maximum highway visibility, pre-leased opportunity.',
    blocks: 'A, B',
    size: '750 Sq.Ft.',
    price: '₹ 1.45 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=300&q=80',
    purpose: 'Both',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: 'Commercial Shop',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 132,
    region: 'Greater Noida',
    sector: 'KNOWLEDGE PARK III',
    details: 'Premium Commercial/Institutional Complex plot opportunity. Gated layout design, near world class colleges and direct metro access point.',
    blocks: 'C, D',
    size: '1000 MTR',
    price: '₹ 8.50 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: 'Commercial Plot',
    agentName: 'Anil Kumar'
  },
  {
    id: 133,
    region: 'Greater Noida',
    sector: 'TECHZONE 4',
    details: '3 BHK Brand New Ultra Luxury Flat (Noida Extension). Prime layout design, massive swimming pool, operational modular clubhouse and gym.',
    blocks: 'A, B',
    size: '1680 Sq.Ft.',
    price: '₹ 1.35 Cr',
    photoUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 81780 97230',
    postedDate: 'Posted Today',
    beds: '3 BHK Flat',
    agentName: 'Gulshan Sharma'
  },
  {
    id: 134,
    region: 'Greater Noida',
    sector: 'SECTOR 10 (W)',
    details: '3 BHK Spacious High-Rise Apartment in Sector 10. Semi-furnished corner unit, excellent natural ventilation, premium wardrobes, ready-to-move.',
    blocks: 'C, D',
    size: '1460 Sq.Ft.',
    price: '₹ 98 Lakhs',
    photoUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=300&q=80',
    purpose: 'Sell',
    contactNumber: '+91 78387 75327',
    postedDate: 'Posted Today',
    beds: '3 BHK Flat',
    agentName: 'Anil Kumar'
  }
];

export const SERVICES = [
  {
    id: 'buy',
    icon: 'Home',
    title: 'Property Buy',
    short: 'Residential & Commercial Property Available.',
    description: 'Find your dream home or a profitable business space. We offer prime residential plots, luxury villas, modern apartments, and premium commercial retail shops/offices in Greater Noida and Yamuna Expressway regions.',
    benefits: ['Verified Titles & Clear Documents', 'Prime Locations with High Appreciation', 'Authority-Approved Safe Plots', 'Excellent Rental Yield Potential']
  },
  {
    id: 'sell',
    icon: 'TrendingUp',
    title: 'Property Sell',
    short: 'Sell Property At Best Market Rates.',
    description: 'Get the absolute maximum return on your real estate investments. Our active network of investors and transparent valuation process guarantees rapid, stress-free property sales at high market prices.',
    benefits: ['Zero Aggressive Commission Markups', 'Direct Selling to Genuine Handpicked Buyers', 'Accurate, Evidence-Based Valuation', 'End-to-End Legal & Registration Work']
  },
  {
    id: 'rent',
    icon: 'Key',
    title: 'Property Rent',
    short: 'Flats, Shops & Offices Available.',
    description: 'Looking to rent? We connect corporate executives, businesses, and families with rental properties. Find fully-furnished and semi-furnished apartments, corporate office spaces, and retail shops.',
    benefits: ['Speedy Matchmaking & Verification', 'Flexible & Standard Lease Agreements', 'Budget-Optimized Rental Solutions', 'Prime Commuting-Friendly Locations']
  },
  {
    id: 'build',
    icon: 'Hammer',
    title: 'Construction',
    short: 'House & Building Construction Services.',
    description: 'Build your dream structure with peace of mind. From architectural blueprint mapping to premium building material supply and master craftsmanship, our construction division handles everything.',
    benefits: ['Premium Certified Building Material', 'Highly Experienced Structural Engineers', 'Timely Project Delivery Guarantee', 'Affordable Project Cost Calculation']
  }
];

export const COMPANY_STATS = [
  { value: '18+', label: 'Years of Trust' },
  { value: '5,000+', label: 'Happy Clients' },
  { value: '1,200+', label: 'Properties Exchanged' },
  { value: '100%', label: 'Verified Listing Rate' }
];

export const OFFICE_CONTACT = {
  name: 'SHARMA PROP MART',
  legalName: 'SHARMA PROPERTIES',
  addressLine1: 'Phase 1 - 166 A Pratap Nagar',
  addressLine2: 'Mayur Vihar Phase-1, New Delhi - 110091',
  detailedAddress: '166 A, 3rd Floor, Above Durbar Restaurant, Pratap Nagar, Mayur Vihar Phase-1, New Delhi - 110091',
  phone: '+91 81780 97230',
  rawPhone: '918178097230',
  phone2: '+91 78387 75327',
  rawPhone2: '917838775327',
  email: 'sharmagulshan431@gmail.com',
  whatsappUrlBase: 'https://wa.me/918178097230'
};

export const WHATSAPP_REPRESENTATIVES = [
  { id: 'desk1', name: 'Inquiry Desk 1', phone: '+91 81780 97230', raw: '918178097230', purpose: 'Quick Chat & Site Visits' },
  { id: 'desk2', name: 'Inquiry Desk 2', phone: '+91 78387 75327', raw: '917838775327', purpose: 'Rates & Sell Bookings' }
];
